export const WEATHER_CODE_DESCRIPTIONS: { [key: number]: { en: string; fr: string } } = {
  0: { en: 'Clear sky', fr: 'Ciel dégagé' },
  1: { en: 'Mainly clear', fr: 'Principalement dégagé' },
  2: { en: 'Partly cloudy', fr: 'Partiellement nuageux' },
  3: { en: 'Overcast', fr: 'Couvert' },
  45: { en: 'Fog', fr: 'Brouillard' },
  48: { en: 'Depositing rime fog', fr: 'Brouillard givrant' },
  51: { en: 'Light drizzle', fr: 'Légère bruine' },
  53: { en: 'Moderate drizzle', fr: 'Bruine modérée' },
  55: { en: 'Dense drizzle', fr: 'Bruine dense' },
  56: { en: 'Light freezing drizzle', fr: 'Légère bruine verglaçante' },
  57: { en: 'Dense freezing drizzle', fr: 'Bruine verglaçante dense' },
  61: { en: 'Slight rain', fr: 'Légère pluie' },
  63: { en: 'Moderate rain', fr: 'Pluie modérée' },
  65: { en: 'Heavy rain', fr: 'Forte pluie' },
  66: { en: 'Light freezing rain', fr: 'Légère pluie verglaçante' },
  67: { en: 'Heavy freezing rain', fr: 'Forte pluie verglaçante' },
  71: { en: 'Slight snow fall', fr: 'Légère chute de neige' },
  73: { en: 'Moderate snow fall', fr: 'Chute de neige modérée' },
  75: { en: 'Heavy snow fall', fr: 'Forte chute de neige' },
  77: { en: 'Snow grains', fr: 'Grains de neige' },
  80: { en: 'Slight rain showers', fr: 'Légères averses de pluie' },
  81: { en: 'Moderate rain showers', fr: 'Averses de pluie modérées' },
  82: { en: 'Violent rain showers', fr: 'Averses de pluie violentes' },
  85: { en: 'Slight snow showers', fr: 'Légères averses de neige' },
  86: { en: 'Heavy snow showers', fr: 'Fortes averses de neige' },
  95: { en: 'Thunderstorm', fr: 'Orage' },
  96: { en: 'Thunderstorm with slight hail', fr: 'Orage avec grêle légère' },
  99: { en: 'Thunderstorm with heavy hail', fr: 'Orage avec grêle lourde' },
};
